import { z } from "zod";

export const DogBreedInfoSchema = z.array(
  z.object({
    name: z.string(),
    image_link: z.string().url(),
    good_with_children: z.number(),
    good_with_other_dogs: z.number(),
    good_with_strangers: z.number(),
    shedding: z.number(),
    grooming: z.number(),
    drooling: z.number(),
    coat_length: z.number(),
    playfulness: z.number(),
    protectiveness: z.number(),
    trainability: z.number(),
    energy: z.number(),
    barking: z.number(),
    min_life_expectancy: z.number(),
    max_life_expectancy: z.number(),
    max_height_male: z.number(),
    max_height_female: z.number(),
    max_weight_male: z.number(),
    max_weight_female: z.number(),
    min_height_male: z.number(),
    min_height_female: z.number(),
    min_weight_male: z.number(),
    min_weight_female: z.number(),
  }),
);
